### PR TITLE
fix : check existing labels in add label command

### LINKED ISSUE #531: [FIX] - The add label command should check existing labels
The command should only be able to add labels that are already present in the repository's settings.

### PR DESCRIPTION
**Pull request by a2937**
Checklist:

- [X] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [X] My pull request has a [descriptive title](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request?id=prepare-a-good-pr-title) (**not** a vague title like `Update index.md`)

Closes #531

This issue has been created as a draft because I am not exactly sure where to get a GitHub token to properly test this command, but the logic seems fairly sound.

### CODE REVIEW

File: src/commands/subcommands/github/handleAddLabels.ts [hunk 1]
```diff
@@ -18,18 +18,38 @@ export const handleAddLabels: Subcommand = {
       const labels = interaction.options.getString("labels", true);
       const labelNames = labels.split(",").map((l) => l.trim());
 
-      await Bot.octokit.issues.addLabels({
-        owner: "freeCodeCamp",
-        issue_number: number,
-        repo,
-        labels: labelNames
-      });
+      const response = await Bot.octokit.request(
```
Comment (naomi-lgbt) [inline src/commands/subcommands/github/handleAddLabels.ts]: We should be able to use `Bot.octokit.issues.listLabelsForRepo()` rather than constructing our own request.

File: src/commands/subcommands/github/handleAddLabels.ts [hunk 2]
```diff
@@ -18,18 +18,38 @@ export const handleAddLabels: Subcommand = {
...
+          repo: repo
+        }
+      );
+
+      const presentLabels = response.data.map((x) => x.name.trim());
+
+      if (
+        labelNames.every((requestedLabel) =>
+          presentLabels.includes(requestedLabel)
+        )
```
Comment (naomi-lgbt) [inline src/commands/subcommands/github/handleAddLabels.ts]: We should invert the logic. And leverage early return patterns.

if (label not valid) {
  interaction.editReply(label don't exist)
  return
}

add label
interaction.editReply(label added)

File: src/commands/subcommands/github/handleAddLabels.ts (hunk 1 above)
Comment (a2937) [reply src/commands/subcommands/github/handleAddLabels.ts]: I think I got it. The method should do exactly what the custom request did.

File: src/commands/subcommands/github/handleAddLabels.ts (hunk 2 above)
Comment (a2937) [reply src/commands/subcommands/github/handleAddLabels.ts]: Understood.

**Review by naomi-lgbt — APPROVED** [review]
