### PR TITLE
bug fix

### LINKED ISSUE #47: [Bug] Server crash when user leaves
**Describe the bug**
When a user leaves, the whole server crashes and needs to be started again

**To Reproduce**
1. Leave the server

**Expected behavior**
Send a leave message to some channel

**Screenshots**
bilde

### PR DESCRIPTION
**Pull request by naomi-lgbt**
Closes #47

### CODE REVIEW

File: src/commands/bootstrap.js [hunk 1]
```diff
@@ -29,7 +29,7 @@ module.exports = function bootstrap({ client, config }) {
 
   client.on('guildMemberRemove', (member) => {
     member.guild.channels.cache
-      .find((ch) => ch.name === 'introduction')
+      .find((ch) => ch.name === 'introductions')
```
Comment (bradtaniguchi) [inline src/commands/bootstrap.js]: This might be more useful as a config setting. (this can be done in another issue/pr)

also, to prevent the server from exploding check that `.find` returns something before calling `.send`. If it **doesn't** find the channel specified log an error about how the "remove channel" wasn't found or something.

**Review by bradtaniguchi — CHANGES_REQUESTED** [review]

File: src/commands/bootstrap.js (hunk 1 above)
Comment (naomi-lgbt) [reply src/commands/bootstrap.js]: Should be corrected now.

**Comment by naomi-lgbt** [comment]
Okay, I tested this code on my bot and it logs the "Channel not found" message and does not crash the server.

File: src/commands/bootstrap.js [hunk 2]
```diff
@@ -27,12 +27,17 @@ module.exports = function bootstrap({ client, config }) {
...
+  client.on('guildMemberRemove', function(member) {
+  const goodbye = member.guild.channels.cache.find(
+    channel => channel.name == 'introductions'
+  );
+  if (goodbye == undefined) {
+    console.log('Channel not found.');
+    return;
+  } else {
+    goodbye.send(`** ${member.user} has left us! :( **`);
+  }
```
Comment (bradtaniguchi) [inline src/commands/bootstrap.js]: Change to just:
```
if (!goodebyeChannel) {
  console.error('goodbye channel not found');
  return;
}
goodebyeChannel.send(/**/);
```

Comment (naomi-lgbt) [reply src/commands/bootstrap.js]: Better? :)

**Review by bradtaniguchi — APPROVED** [review]
